// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using joins;

namespace joins.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20191112192957_employees")]
    partial class employees
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("joins.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Department_Name");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("joins.Models.employees", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Department_Id");

                    b.Property<int?>("DepartmentsId");

                    b.Property<string>("Full_Name");

                    b.Property<bool>("Full_Time");

                    b.Property<string>("Job_Position");

                    b.Property<int>("Phone_Extension");

                    b.Property<int>("Salary");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentsId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("joins.Models.employees", b =>
                {
                    b.HasOne("joins.Models.Department", "Departments")
                        .WithMany("Employee")
                        .HasForeignKey("DepartmentsId");
                });
#pragma warning restore 612, 618
        }
    }
}
